// <auto-generated />
using Buscandomitrago.Domain.Utils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buscandomitrago.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Buscandomitrago.Domain.Models.Drink", b =>
                {
                    b.Property<string>("idDrink")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("dateModified")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strAlcoholic")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strCategory")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strCreativeCommonsConfirmed")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strDrink")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strDrinkAlternate")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strDrinkThumb")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strGlass")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strIBA")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strImageAttribution")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strImageSource")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strIngredient1")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("strIngredient10")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("strIngredient11")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("strIngredient12")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("strIngredient13")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("strIngredient14")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("strIngredient15")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("strIngredient2")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("strIngredient3")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("strIngredient4")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("strIngredient5")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("strIngredient6")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("strIngredient7")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("strIngredient8")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("strIngredient9")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("strInstructions")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strInstructionsDE")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strInstructionsES")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strInstructionsFR")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strInstructionsIT")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strInstructionsZH_HANS")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strInstructionsZH_HANT")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strMeasure1")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strMeasure10")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strMeasure11")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strMeasure12")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strMeasure13")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strMeasure14")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strMeasure15")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strMeasure2")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strMeasure3")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strMeasure4")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strMeasure5")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strMeasure6")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strMeasure7")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strMeasure8")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strMeasure9")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strTags")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("strVideo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("idDrink");

                    b.ToTable("Drinks");
                });
#pragma warning restore 612, 618
        }
    }
}
